// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAutoStart() {
  return window['go']['main']['App']['CheckAutoStart']();
}

export function GetDefaultConfig() {
  return window['go']['main']['App']['GetDefaultConfig']();
}

export function GetServerIP() {
  return window['go']['main']['App']['GetServerIP']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsServerRunning() {
  return window['go']['main']['App']['IsServerRunning']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function StartFTPServer(arg1) {
  return window['go']['main']['App']['StartFTPServer'](arg1);
}

export function StopFTPServer() {
  return window['go']['main']['App']['StopFTPServer']();
}
